/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as NewsRouteImport } from './routes/news'
import { Route as InnovationRouteImport } from './routes/innovation'
import { Route as ForStudentsRouteImport } from './routes/for-students'
import { Route as ForPartnersRouteImport } from './routes/for-partners'
import { Route as ForInnovatorsRouteImport } from './routes/for-innovators'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as InnovationIndexRouteImport } from './routes/innovation.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as InnovationSlugRouteImport } from './routes/innovation.$slug'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationRoute = InnovationRouteImport.update({
  id: '/innovation',
  path: '/innovation',
  getParentRoute: () => rootRouteImport,
} as any)
const ForStudentsRoute = ForStudentsRouteImport.update({
  id: '/for-students',
  path: '/for-students',
  getParentRoute: () => rootRouteImport,
} as any)
const ForPartnersRoute = ForPartnersRouteImport.update({
  id: '/for-partners',
  path: '/for-partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ForInnovatorsRoute = ForInnovatorsRouteImport.update({
  id: '/for-innovators',
  path: '/for-innovators',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const InnovationIndexRoute = InnovationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InnovationRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const InnovationSlugRoute = InnovationSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InnovationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/events': typeof EventsRoute
  '/for-innovators': typeof ForInnovatorsRoute
  '/for-partners': typeof ForPartnersRoute
  '/for-students': typeof ForStudentsRoute
  '/innovation': typeof InnovationRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/resources': typeof ResourcesRoute
  '/support': typeof SupportRoute
  '/innovation/$slug': typeof InnovationSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/innovation/': typeof InnovationIndexRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/events': typeof EventsRoute
  '/for-innovators': typeof ForInnovatorsRoute
  '/for-partners': typeof ForPartnersRoute
  '/for-students': typeof ForStudentsRoute
  '/programs': typeof ProgramsRoute
  '/resources': typeof ResourcesRoute
  '/support': typeof SupportRoute
  '/innovation/$slug': typeof InnovationSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/innovation': typeof InnovationIndexRoute
  '/news': typeof NewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/events': typeof EventsRoute
  '/for-innovators': typeof ForInnovatorsRoute
  '/for-partners': typeof ForPartnersRoute
  '/for-students': typeof ForStudentsRoute
  '/innovation': typeof InnovationRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/resources': typeof ResourcesRoute
  '/support': typeof SupportRoute
  '/innovation/$slug': typeof InnovationSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/innovation/': typeof InnovationIndexRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/courses'
    | '/events'
    | '/for-innovators'
    | '/for-partners'
    | '/for-students'
    | '/innovation'
    | '/news'
    | '/programs'
    | '/resources'
    | '/support'
    | '/innovation/$slug'
    | '/news/$slug'
    | '/innovation/'
    | '/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/courses'
    | '/events'
    | '/for-innovators'
    | '/for-partners'
    | '/for-students'
    | '/programs'
    | '/resources'
    | '/support'
    | '/innovation/$slug'
    | '/news/$slug'
    | '/innovation'
    | '/news'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/courses'
    | '/events'
    | '/for-innovators'
    | '/for-partners'
    | '/for-students'
    | '/innovation'
    | '/news'
    | '/programs'
    | '/resources'
    | '/support'
    | '/innovation/$slug'
    | '/news/$slug'
    | '/innovation/'
    | '/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  EventsRoute: typeof EventsRoute
  ForInnovatorsRoute: typeof ForInnovatorsRoute
  ForPartnersRoute: typeof ForPartnersRoute
  ForStudentsRoute: typeof ForStudentsRoute
  InnovationRoute: typeof InnovationRouteWithChildren
  NewsRoute: typeof NewsRouteWithChildren
  ProgramsRoute: typeof ProgramsRoute
  ResourcesRoute: typeof ResourcesRoute
  SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation': {
      id: '/innovation'
      path: '/innovation'
      fullPath: '/innovation'
      preLoaderRoute: typeof InnovationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-students': {
      id: '/for-students'
      path: '/for-students'
      fullPath: '/for-students'
      preLoaderRoute: typeof ForStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-partners': {
      id: '/for-partners'
      path: '/for-partners'
      fullPath: '/for-partners'
      preLoaderRoute: typeof ForPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-innovators': {
      id: '/for-innovators'
      path: '/for-innovators'
      fullPath: '/for-innovators'
      preLoaderRoute: typeof ForInnovatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/innovation/': {
      id: '/innovation/'
      path: '/'
      fullPath: '/innovation/'
      preLoaderRoute: typeof InnovationIndexRouteImport
      parentRoute: typeof InnovationRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/innovation/$slug': {
      id: '/innovation/$slug'
      path: '/$slug'
      fullPath: '/innovation/$slug'
      preLoaderRoute: typeof InnovationSlugRouteImport
      parentRoute: typeof InnovationRoute
    }
  }
}

interface InnovationRouteChildren {
  InnovationSlugRoute: typeof InnovationSlugRoute
  InnovationIndexRoute: typeof InnovationIndexRoute
}

const InnovationRouteChildren: InnovationRouteChildren = {
  InnovationSlugRoute: InnovationSlugRoute,
  InnovationIndexRoute: InnovationIndexRoute,
}

const InnovationRouteWithChildren = InnovationRoute._addFileChildren(
  InnovationRouteChildren,
)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  EventsRoute: EventsRoute,
  ForInnovatorsRoute: ForInnovatorsRoute,
  ForPartnersRoute: ForPartnersRoute,
  ForStudentsRoute: ForStudentsRoute,
  InnovationRoute: InnovationRouteWithChildren,
  NewsRoute: NewsRouteWithChildren,
  ProgramsRoute: ProgramsRoute,
  ResourcesRoute: ResourcesRoute,
  SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
