/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as NewsRouteImport } from './routes/news'
import { Route as InnovationRouteImport } from './routes/innovation'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SupportRoute = SupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
    id: '/news',
    path: '/news',
    getParentRoute: () => rootRouteImport,
} as any)
const InnovationRoute = InnovationRouteImport.update({
    id: '/innovation',
    path: '/innovation',
    getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
    '/': typeof IndexRoute
    '/about': typeof AboutRoute
    '/contact': typeof ContactRoute
    '/courses': typeof CoursesRoute
    '/events': typeof EventsRoute
    '/innovation': typeof InnovationRoute
    '/news': typeof NewsRoute
    '/support': typeof SupportRoute
}
export interface FileRoutesByTo {
    '/': typeof IndexRoute
    '/about': typeof AboutRoute
    '/contact': typeof ContactRoute
    '/courses': typeof CoursesRoute
    '/events': typeof EventsRoute
    '/innovation': typeof InnovationRoute
    '/news': typeof NewsRoute
    '/support': typeof SupportRoute
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport
    '/': typeof IndexRoute
    '/about': typeof AboutRoute
    '/contact': typeof ContactRoute
    '/courses': typeof CoursesRoute
    '/events': typeof EventsRoute
    '/innovation': typeof InnovationRoute
    '/news': typeof NewsRoute
    '/support': typeof SupportRoute
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath
    fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/courses'
    | '/events'
    | '/innovation'
    | '/news'
    | '/support'
    fileRoutesByTo: FileRoutesByTo
    to:
    | '/'
    | '/about'
    | '/contact'
    | '/courses'
    | '/events'
    | '/innovation'
    | '/news'
    | '/support'
    id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/courses'
    | '/events'
    | '/innovation'
    | '/news'
    | '/support'
    fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute
    AboutRoute: typeof AboutRoute
    ContactRoute: typeof ContactRoute
    CoursesRoute: typeof CoursesRoute
    EventsRoute: typeof EventsRoute
    InnovationRoute: typeof InnovationRoute
    NewsRoute: typeof NewsRoute
    SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/support': {
            id: '/support'
            path: '/support'
            fullPath: '/support'
            preLoaderRoute: typeof SupportRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/news': {
            id: '/news'
            path: '/news'
            fullPath: '/news'
            preLoaderRoute: typeof NewsRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/innovation': {
            id: '/innovation'
            path: '/innovation'
            fullPath: '/innovation'
            preLoaderRoute: typeof InnovationRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/events': {
            id: '/events'
            path: '/events'
            fullPath: '/events'
            preLoaderRoute: typeof EventsRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/courses': {
            id: '/courses'
            path: '/courses'
            fullPath: '/courses'
            preLoaderRoute: typeof CoursesRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/contact': {
            id: '/contact'
            path: '/contact'
            fullPath: '/contact'
            preLoaderRoute: typeof ContactRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/about': {
            id: '/about'
            path: '/about'
            fullPath: '/about'
            preLoaderRoute: typeof AboutRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/': {
            id: '/'
            path: '/'
            fullPath: '/'
            preLoaderRoute: typeof IndexRouteImport
            parentRoute: typeof rootRouteImport
        }
    }
}

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    AboutRoute: AboutRoute,
    ContactRoute: ContactRoute,
    CoursesRoute: CoursesRoute,
    EventsRoute: EventsRoute,
    InnovationRoute: InnovationRoute,
    NewsRoute: NewsRoute,
    SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>()